### ISSUE TITLE
Green Text difficult to read in dark theme

### ISSUE THREAD

**Issue by ryman1** [b4dpxl/Burp-ResponseGrepper#1]
When running Burp with the darcula theme the text can be very tough to read.

https://www.dropbox.com/s/kla8ltiku8kju5x/2020-01-10_18-01-23.png

**Comment by b4dpxl** [comment]
Hi @ryman1, thanks for raising this. I've just pushed an update which hopefully fixes this, by attempting to read the theme from the burp config file.
